#!/bin/sh
set -e
rm -f parm.aux
noweave -delay -index parm.nw >parm.tex; pdflatex parm; pdflatex parm; pdflatex parm
noweave -delay -filter l2h -index -html parm.nw | htmltoc > parm.html
for x in nt-parm nw-parm-{pre,post}idx; do
  notangle -L -R${x}.cpp parm.nw >${x}.cpp
  g++ --std=c++98 -O2 -Wall -Wextra -o $x{,.cpp}
  g++ -O2 -Wall -Wextra -o $x{,.cpp}
done
notangle -Rmk-noroots parm.nw | sh > noroots-parm
chmod +x noroots-parm
